"""Human-readable projection of a compiled DOMAIN_VIEW."""

from __future__ import annotations

from collections import defaultdict

from app.domain.intelligence.models import DomainView, KnowledgeLayer, SourceType


def render_domain_view_markdown(view: DomainView) -> str:
    layers: dict[str, list[str]] = defaultdict(list)
    for claim in view.active_claims():
        layers[claim.layer.value].append(
            f"- `{claim.claim_id}` ({claim.source_type.value}, {claim.knowledge_class.value}"
            f"{f', {claim.authority.value}' if claim.authority.value != 'NONE' else ''}"
            f"): {claim.statement}"
        )

    experiential = [
        claim
        for claim in view.active_claims()
        if claim.source_type is SourceType.PROMOTED_EXPERIENCE
    ]
    if experiential:
        learned_block = "\n".join(
            (
                f"- `{claim.claim_id}` "
                f"[{claim.authority.value} / {claim.scope.level.value}]: "
                f"{claim.statement}"
            )
            for claim in experiential
        )
    else:
        learned_block = "0 PROMOTED EXPERIENTIAL LESSONS"

    layer_order = [layer.value for layer in KnowledgeLayer]
    layer_sections = []
    for name in layer_order:
        items = layers.get(name) or ["- _(none)_"]
        layer_sections.append(f"### {name}\n\n" + "\n".join(items))

    versions = view.source_versions
    return f"""# PreM3 DOMAIN_VIEW

> Generated snapshot. Do not edit this file by hand.
> Source of truth: structured catalogs + `app/domain/intelligence` builder.

## Header

| Field | Value |
|---|---|
| Domain View Version | `{view.domain_view_version}` |
| Generated At | `{view.generated_at}` |
| Product Context Version | `{versions.product_context_version}` |
| MMM Boot Context Version | `{versions.mmm_boot_context_version}` |
| Rule Registry Version | `{versions.rule_registry_version}` |
| Intelligence Registry Version | `{versions.intelligence_registry_version}` |
| Intelligence Version | `{versions.intelligence_version}` |
| Source Verification Date | `{versions.source_verification_date}` |
| Promoted Lesson Set Version | `{view.promoted_lesson_set_version}` |
| Promoted Lesson Count | `{view.promoted_lesson_count}` |
| Content Fingerprint | `{view.content_fingerprint}` |
| Previous Domain View Version | `{view.previous_domain_view_version or "none"}` |
| Status | `{view.status}` |
| Active Claim Count | `{len(view.active_claims())}` |

## Experiential learning

{learned_block}

This section reports **PROMOTED_EXPERIENCE** only. Official source or policy
updates are domain-knowledge updates, not learning.

## Knowledge layers

Precedence: `MERIDIAN_NORMATIVE` > `PREM3_POLICY` > `VERIFIED_DOMAIN_GUIDANCE` >
`VALIDATED_EXPERIENCE_PATTERN` > `ADVISORY_LEARNED_PATTERN` > `OBSERVATION`.

{chr(10).join(layer_sections)}

## How to inspect

- Machine representation: `app/domain/intelligence/data/current/domain_view.json`
- Builder: `python -m app.domain.intelligence`
- Architecture: `docs/context/domain-view/README.md`
"""
