"""DOMAIN_VIEW builder, fingerprint, diff, and authority-boundary tests."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from app.domain.intelligence.builder import (
    CURRENT_JSON,
    MARKDOWN_PATH,
    build_domain_view,
    summarize_domain_view,
)
from app.domain.intelligence.diff import classify_learned_vs_source_update, diff_domain_views
from app.domain.intelligence.fingerprint import fingerprint_view_content
from app.domain.intelligence.models import (
    ClaimScope,
    DomainView,
    DomainViewError,
    KnowledgeClass,
    LearnedAuthority,
    PromotedLessonInput,
    PromotionStatus,
    ScopeLevel,
    SourceType,
)

ROOT = Path(__file__).resolve().parents[2]
PRODUCT = (ROOT / "docs/context/PREM3_PRODUCT_CONTEXT.md").read_text(encoding="utf-8")


def _lesson(**overrides: object) -> PromotedLessonInput:
    payload = {
        "lesson_id": "fixture-routing-gqv",
        "statement": (
            "When GQV, paid search, and upper-funnel media coexist, trigger semantic review."
        ),
        "knowledge_class": KnowledgeClass.ADVISORY_LEARNED_PATTERN,
        "authority": LearnedAuthority.ROUTING_HINT,
        "scope": ClaimScope(level=ScopeLevel.GLOBAL),
        "source_refs": ["fixture"],
        "evidence": ["synthetic unit fixture — not production learning"],
        "regression_status": "PASSED",
        "behavior_effect": "Ask a semantic-readiness question before GQV advice.",
        "promotion_status": PromotionStatus.PROMOTED,
        "last_validated_at": "2026-08-16",
    }
    payload.update(overrides)
    return PromotedLessonInput.model_validate(payload)


def test_v1_has_zero_promoted_lessons() -> None:
    view = build_domain_view(generated_at="2026-08-16T00:00:00+00:00")
    assert view.promoted_lesson_count == 0
    assert view.domain_view_version == "1.0.0"
    assert all(claim.source_type is not SourceType.PROMOTED_EXPERIENCE for claim in view.claims)
    markdown = MARKDOWN_PATH.read_text(encoding="utf-8")
    assert "0 PROMOTED EXPERIENTIAL LESSONS" in markdown
    assert "Do not edit this file by hand" in markdown


def test_generated_markdown_matches_machine_view() -> None:
    machine = DomainView.model_validate_json(CURRENT_JSON.read_text(encoding="utf-8"))
    markdown = MARKDOWN_PATH.read_text(encoding="utf-8")
    assert machine.content_fingerprint in markdown
    assert machine.domain_view_version in markdown
    assert str(machine.promoted_lesson_count) in markdown


def test_builder_is_idempotent() -> None:
    first = build_domain_view(generated_at="2026-08-16T00:00:00+00:00")
    second = build_domain_view(previous=first, generated_at="2026-08-17T00:00:00+00:00")
    assert first.content_fingerprint == second.content_fingerprint
    assert first.domain_view_version == second.domain_view_version
    assert fingerprint_view_content(first) == first.content_fingerprint


def test_promoted_lesson_enters_view() -> None:
    baseline = build_domain_view(generated_at="2026-08-16T00:00:00+00:00")
    updated = build_domain_view(
        previous=baseline,
        extra_lessons=[_lesson()],
        generated_at="2026-08-16T00:00:00+00:00",
    )
    assert updated.promoted_lesson_count == 1
    assert updated.content_fingerprint != baseline.content_fingerprint
    assert updated.domain_view_version != baseline.domain_view_version
    claim = next(
        item for item in updated.claims if item.source_type is SourceType.PROMOTED_EXPERIENCE
    )
    assert claim.scope.level is ScopeLevel.GLOBAL
    assert claim.authority is LearnedAuthority.ROUTING_HINT
    assert "synthetic unit fixture" in claim.evidence[0]


def test_rejected_lesson_does_not_enter() -> None:
    baseline = build_domain_view(generated_at="2026-08-16T00:00:00+00:00")
    rejected = _lesson(
        promotion_status=PromotionStatus.FAILED_REGRESSION,
        regression_status="FAILED",
    )
    updated = build_domain_view(
        previous=baseline,
        extra_lessons=[rejected],
        generated_at="2026-08-16T00:00:00+00:00",
    )
    assert updated.promoted_lesson_count == 0
    assert updated.content_fingerprint == baseline.content_fingerprint


def test_normative_conflict_is_rejected() -> None:
    baseline = build_domain_view(generated_at="2026-08-16T00:00:00+00:00")
    with pytest.raises(DomainViewError, match="non-negative"):
        build_domain_view(
            previous=baseline,
            extra_lessons=[
                _lesson(
                    lesson_id="bad-negative",
                    statement="Negative media is acceptable for provider X.",
                )
            ],
        )


def test_missing_media_policy_conflict_is_rejected() -> None:
    with pytest.raises(DomainViewError, match="missing-media"):
        build_domain_view(
            extra_lessons=[
                _lesson(
                    lesson_id="bad-zero",
                    statement="Missing provider rows always mean zero.",
                )
            ]
        )


def test_organization_scope_does_not_enter_global() -> None:
    with pytest.raises(DomainViewError, match="organization-scoped"):
        build_domain_view(
            extra_lessons=[
                _lesson(scope=ClaimScope(level=ScopeLevel.ORGANIZATION, value="org-x"))
            ]
        )


def test_run_fact_is_not_domain_knowledge() -> None:
    with pytest.raises(DomainViewError, match="run"):
        build_domain_view(
            extra_lessons=[
                _lesson(
                    lesson_id="run-fact",
                    statement="Dataset A has 524 rows.",
                    scope=ClaimScope(level=ScopeLevel.RUN, value="run-1"),
                )
            ]
        )


def test_final_modeling_lesson_is_forbidden() -> None:
    with pytest.raises(DomainViewError, match="ModelSpec|priors"):
        build_domain_view(
            extra_lessons=[
                _lesson(
                    lesson_id="bad-knots",
                    statement="Use 130 knots for future final models.",
                    authority=LearnedAuthority.AUTO_SAFE_POLICY,
                )
            ]
        )


def test_causal_overgeneralization_is_rejected() -> None:
    with pytest.raises(DomainViewError, match="causal role"):
        build_domain_view(
            extra_lessons=[
                _lesson(
                    lesson_id="bad-gqv",
                    statement="GQV is always a mediator when upper-funnel media exists.",
                )
            ]
        )


def test_privacy_markers_rejected() -> None:
    with pytest.raises(DomainViewError, match="customer"):
        build_domain_view(
            extra_lessons=[
                _lesson(
                    lesson_id="leak",
                    statement="organization_id acme always uses Monday weeks.",
                )
            ]
        )


def test_diff_separates_source_update_from_learning() -> None:
    baseline = build_domain_view(generated_at="2026-08-16T00:00:00+00:00")
    learned = build_domain_view(
        previous=baseline,
        extra_lessons=[_lesson()],
        generated_at="2026-08-16T00:00:00+00:00",
    )
    diff = diff_domain_views(baseline, learned)
    classified = classify_learned_vs_source_update(diff)
    assert classified["experience_learned"]
    assert any(item.startswith("DV-EXP-") for item in classified["experience_learned"])
    source_only = build_domain_view(generated_at="2026-08-16T00:00:00+00:00")
    mutated = source_only.model_copy(deep=True)
    mutated.claims[0].statement = "Updated official wording."
    source_diff = diff_domain_views(source_only, mutated)
    source_classified = classify_learned_vs_source_update(source_diff)
    assert source_classified["experience_learned"] == []
    assert source_classified["source_or_policy_updates"]


def test_global_serialized_view_has_no_customer_fields() -> None:
    payload = json.loads(CURRENT_JSON.read_text(encoding="utf-8"))
    blob = json.dumps(payload).lower()
    for marker in ("organization_id", "customer_id", "account_id", "524 rows"):
        assert marker not in blob
    view = DomainView.model_validate(payload)
    assert view.promoted_lesson_count == 0


def test_duplicate_claim_ids_fail_closed() -> None:
    with pytest.raises(DomainViewError, match="duplicate"):
        build_domain_view(extra_lessons=[_lesson(), _lesson()])


def test_summary_does_not_dump_all_claims() -> None:
    view = build_domain_view(generated_at="2026-08-16T00:00:00+00:00")
    summary = summarize_domain_view(view)
    assert "claims" not in summary
    assert summary["promoted_lesson_count"] == 0
    assert summary["claim_count"] == len(view.active_claims())


def test_product_context_does_not_call_source_sync_learning() -> None:
    assert "domain knowledge was updated" in PRODUCT
    assert "I currently have no promoted experiential lessons." in PRODUCT
    assert "I don't treat memory as learning." in PRODUCT
