"""Canonical M3 run state machine values."""

from enum import StrEnum


class RunStage(StrEnum):
    NEW = "NEW"
    DISCOVERING = "DISCOVERING"
    PROFILING = "PROFILING"
    MAPPING = "MAPPING"
    ASSESSING = "ASSESSING"
    WAITING_FOR_APPROVAL = "WAITING_FOR_APPROVAL"
    REMEDIATING = "REMEDIATING"
    VALIDATING = "VALIDATING"
    PUBLISHING = "PUBLISHING"
    MODEL_READY = "MODEL_READY"
    WAITING_FOR_MODEL_APPROVAL = "WAITING_FOR_MODEL_APPROVAL"
    MODELING = "MODELING"
    FAILED = "FAILED"
    LEARNING = "LEARNING"
    COMPLETE = "COMPLETE"


TERMINAL_STAGES = {RunStage.MODEL_READY, RunStage.FAILED, RunStage.COMPLETE}
